In [1]:
import numpy as np

a= np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [7]:
import time
a=np.random.rand(1000000)
b=np.random.rand(1000000)

tic=time.time()
c=np.dot(a,b)
toc=time.time()
print("Time:" +str(1000*(toc-tic))+" ms")

c=0
tic=time.time()
for i in range(1000000):
    c+=a[i]*b[i]
toc=time.time()
print("Time:" +str(1000*(toc-tic))+" ms")

c=0
tic=time.time()
i=0
while(i<1000000):
    c+=a[i]*b[i]
    i+=1
toc=time.time()
print("Time:" +str(1000*(toc-tic))+" ms")

Time:3.7255287170410156 ms
Time:674.8995780944824 ms
Time:709.0761661529541 ms


In [2]:
import numpy as np

A=np.array([[56.0,0.0,4.4,68.0],
           [1.2,104.0,52.0,8.0],
           [1.8,135.0,99.0,0.9]])
print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [3]:
cal= A.sum(axis=0)
print(cal)

[ 59.  239.  155.4  76.9]


In [4]:
percentage=100*A/cal.reshape(1,4)

In [5]:
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


In [6]:
a=np.random.randn(5)
print(a)

[-2.04516151  0.97310796  1.17731889 -0.11267977 -0.76390278]


In [7]:
print(a.shape)

(5,)


In [8]:
print(a.T)


[-2.04516151  0.97310796  1.17731889 -0.11267977 -0.76390278]


In [9]:
print(np.dot(a,a.T))

7.111948633018721


In [10]:
a=np.random.rand(5,1)
print(a)

[[0.45415034]
 [0.40609013]
 [0.15423453]
 [0.894667  ]
 [0.86315597]]


In [11]:
print(a.T)

[[0.45415034 0.40609013 0.15423453 0.894667   0.86315597]]


In [13]:
print(np.dot(a,a.T))

[[0.20625253 0.18442597 0.07004566 0.40631332 0.39200258]
 [0.18442597 0.1649092  0.06263312 0.36331544 0.35051912]
 [0.07004566 0.06263312 0.02378829 0.13798854 0.13312845]
 [0.40631332 0.36331544 0.13798854 0.80042904 0.77223716]
 [0.39200258 0.35051912 0.13312845 0.77223716 0.74503823]]


In [14]:
a = np.random.randn(12288, 150) # a.shape = (12288, 150)
b = np.random.randn(150, 45) # b.shape = (150, 45)
c = np.dot(a,b)
print(c.shape)

(12288, 45)


In [15]:
a = np.random.randn(4, 3) # a.shape = (4, 3)
b = np.random.randn(3, 2) # b.shape = (3, 2)
c = a*b
print(c.shape)

ValueError: operands could not be broadcast together with shapes (4,3) (3,2) 

In [17]:
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
c = a*b
print(c.shape)

(3, 3)
